### ISSUE TITLE
Option to ignore all struct fields not explicitly tagged via struct tag

### ISSUE THREAD

**Issue by annismckenzie** [go-playground/form#10]
In the README there's a section about ignoring fields by tagging them with `form:"-"`. Would it be possible to add an option to the decoder (like `SetTagName(tagName string)`) to ignore all struct fields not explicitly tagged with `form:"fieldName"` (or the custom tag name if set)?

The problem I see is the unintended injection of data because this library is used with user-generated content and accepts form data. Having a language like Go that is strictly typed goes a long way but I do have to go through all of my models and tag them with `form:"-"`. Still, I know this is my fault and want to thank you for this awesome library!

The reason I'm asking is that I'm also using these structs that are filled with form data to also transform the data for later usage. Sometimes there's additional fields I add that need to be public to use within the app but are not supposed to be accepted via the form data. I'm also always tagging all fields I accept even if the form field's name is the lowercased version of the struct field name (so technically, I wouldn't have to add the struct tag) but you immediately see what's accepted via a form and what's not when looking at the struct definition.

If this is a request you'd rather not implement then a few pointers on how to make this safer for me or where you'd start looking in the code. :)

**Comment by joeybloggs** [comment]
Hello @annismckenzie 

I see how it may be beneficial to add and explicit mode for some, Think it would be pretty easy, and would also make sense to add to the encoder portion as well.

Just need to add a function say `SetMode(mode DecoderMode)` ( DecoderMode being an enum type, just in case of maybe future modes to be added ) and your mode would be `DecodeExplicit`

and then in [here](https://github.com/go-playground/form/blob/master/cache.go#L75) check the mode and if explicit then when `name - aka the tag value` is blank continue, just like ignore in the `DecodeDefault` mode. And as an added bonus won't affect performance due to this being in the struct cache portion, and only parsed once.

It may take me a few days to get to it as I'm trying to finish up a few other projects, but will look into it when I get a chance; P.S. if you need it sooner, I would definitely accept a pull request ( with tests ) :)

**Comment by annismckenzie** [comment]
Thanks for taking the time to write this up! And yes, I will take a stab at it later to get into the codebase. :]

**Comment by joeybloggs** [comment]
hey @annismckenzie 

just so you know I implemented this in release [v2.2.0](https://github.com/go-playground/form/releases/tag/v2.2.0)

please try it out and let me know if this is all you need 😄

**Comment by annismckenzie** [comment]
You're awesome! :dancers: I will take a look!

**Comment by annismckenzie** [comment]
Duh, I'm such a dummy. Just turned on the explicit mode and my whole test suite broke. Namely there are certain structs where I don't have control over the tags (gRPC's compiled proto files) that I'm using in my form structs as well and where I don't want to duplicate whole files (also, these are statically typed so I'm fine with and know what's settable and what's not). Booh. So, while this certainly is a feature that has a use case I can't use it now. So so dumb of me. Still, thanks for implementing this this quickly – I will look at disabling this in the embedding struct's tags for that field, write a few tests and maybe we can have a partial explicit mode that can be activated like this on a per-field basis. That way, I could turn this on globally and disable it for these cases where I do want the implicit mode – this should only go one level deep and disable it for that struct only. You may resolve this issue.

Again, thank you!

**Comment by joeybloggs** [comment]
no problems @annismckenzie 

just an idea, but you could have more than once instance of `decoder` or `encoder` and set one instance to Explicit and then you could use each where needed :)

**Comment by annismckenzie** [comment]
That is a very very good suggestion – thanks! 👯
