### ISSUE TITLE
How to fetch errors to End user?

### ISSUE THREAD

**Issue by mrLSD** [go-playground/form#13]
I want using your awesome libraries: form + validation
Let's imagine common situation:

HTML:
```
<form method="POST">
  <input type="text" name="Name" value="joeybloggs"/>
  <input type="text" name="Age" value="myage"/>
</form>
```

Go code:
```

// User contains user information
type User struct {
    Name        string
    Age         uint8
}


// use a single instance of Decoder, it caches struct info
var decoder *form.Decoder

func main() {
    decoder = form.NewDecoder()

    // this simulates the results of http.Request's ParseForm() function
    values := parseForm()

    var user User

    // must pass a pointer
    err := decoder.Decode(&user, values)
    if err != nil {
        log.Panic(err)
    }

    fmt.Printf("%#v\n", user)
}

// this simulates the results of http.Request's ParseForm() function
func parseForm() url.Values {
    return url.Values{
        "Name":                []string{"joeybloggs"},
        "Age":                 []string{"myage"},
    }
}

```
It's error message:

> "Field Namespace:Age ERROR:Invalid Integer Value 'myage' Type 'uint8' Namespace 'Age'"

But useful situation to indicate end-user about validation problem.
At the example I need indicate field Age with message something like: `please enter correct age.`

What you think about that?

**Comment by danhardman** [comment]
If there's errors decoding the request, it's because you either constructed the form wrong, or your users are putting in shitty values. Return an error saying bad request.

If you want more detailed errors, stick a Validate() func or OK() func on your User struct that checks all its values are valid and returns a slice of errors if any values are wrong, then you can pass those down to the user.

I'd recommend adding something like ParsleyJS to your forms to stop users inputting invalid values before they get to the server

**Comment by joeybloggs** [comment]
Hey @mrLSD 

@danhardman's answer is part of the answer, there should definitely be some sort of logic client side to disallow bad input, however that's not always possible and sometimes things get missed.

form's error's are really a map of the fields namespace in the struct and the actual error [see here](https://github.com/go-playground/form/blob/master/form_decoder.go#L15) and you can, based on the maps key(the field), create your own error message for each field.

because you mentioned you wanted to use form + validator, there are actually two other ways to do this this which I recommend over using the form's errors because they will work for not only form parsing but JSON or any other protocol.

use the error returned from form, but only as an indication that some bad data has been received and perhaps, depending how your code is structured, skip right to the validation.

then use validator to validate the data within the struct and receive it's errors, this is where you will have two options.

1. Use validators errors which is actually an array of [FieldError](https://github.com/go-playground/validator/blob/v9/errors.go#L37) and [FieldError](https://github.com/go-playground/validator/blob/v9/errors.go#L83) contains allot of information that one can use to create their own validation errors.

2. This one can have a little more setup but take my word for it, once it's setup it makes errors a breeze as I use this approach myself; ironically enough this approach required the use of [universal-translator](https://github.com/go-playground/universal-translator) and [locales](https://github.com/go-playground/locales) there is a small [example](https://github.com/go-playground/validator/blob/v9/examples/translations/main.go) of how to use it. So validator will translate proper i18n error messages with this approach and best of all can tie right into making your whole site i18n and l10n capable. I currently only have translations for built in validation tags for locale "en" but anyone can register their own.

I'm sure you may have questions, please don't hesitate to ask; I really recommend option 2, it's worth it.

**Comment by mrLSD** [comment]
@danhardman, thank you for the recommendation!

@joeybloggs, excellent answer! I'll try second variant.
Thank you!
