### ISSUE TITLE
CustomTypeFunc is not called when struct contains keys in query

### ISSUE THREAD

**Issue by fastest963** [go-playground/form#14]
If you have a query of `b[0].Foo=1&b[0].Bar=2` and `b` is a custom struct then my CustomTypeFunc won't be called. However, if the query is `b[0]=Foo%3D1%26Bar%3D2` then it works as expected, but I can't expect the caller to know which structs are custom and which aren't.

Test/example case:
```
package main

import (
	"net/url"
	"github.com/go-playground/form"
)

type B struct {
	C string
	d interface{}
}

type A struct {
	B []B
}

func main() {
	d := form.NewDecoder()
	d.RegisterCustomTypeFunc(func(s []string) (interface{}, error) {
		b := B{}
		q, err := url.ParseQuery(s[0])
		if err != nil {
			return nil, err
		}
		b.C = q.Get("C")
		if b.C == "foo" {
			// obviously you could use d.Decode again, but this is an example
			b.d = struct {
				E string
			}{q.Get("E")}
		}
		return b, nil
	}, B{})

	q := url.Values{}
	q.Set("B[0].C", "foo")
	q.Set("B[0].E", "bar")
	a := &A{}
	d.Decode(a, q)
	// RegisterCustomTypeFunc is never called
	// a is &{B:[{C:foo d:<nil>}]}

	q = url.Values{}
	q.Set("B[0]", "C=foo&E=bar")
	a = &A{}
	d.Decode(a, q)
	// RegisterCustomTypeFunc is called
	// a is &{B:[{C:foo d:{E:bar}}]}
}
```

**Comment by joeybloggs** [comment]
Hey @fastest963 thanks for reporting,

I think I know what's going on, I never thought anyone would use the custom type function in this manner... quite interesting :) it's really used to map single value types or primitives, but I can see how this would be useful.

I'll take a look at it tomorrow afternoon and see what I can come up with to make this work.

The crux of why the custom function doesn't get called in your example is that when it checks `B[0]`'s value it is blank and so never calls the custom function, because there is nothing to set for `B` itself but rather only it's fields. And in the second example `B[0]` does have a value and so calls the custom function.

I honestly don't know if I can make it work as even if I get it calling the custom function the values for `C` and `E` wouldn't be passed to it because they are separate values for other fields.

Let me take a look regardless :)

**Comment by fastest963** [comment]
> I honestly don't know if I can make it work as even if I get it calling the custom function the values for C and E wouldn't be passed to it because they are separate values for other fields.

Yeah after glancing at the code, I realize that would be pretty hard to even know that those fields are there to pass the function. Ideally I could get all of the fields that were tried to set on `B[0]` in the form of the `[]string` but that's probably a breaking change so I'm not sure. This might just not be realistic.

Right now, in the interim, I have a function that collects all of the `B[0].*` fields and then combines them into a new `url.Values` and then sets them as `B[0]`. Basically doing what the second block at code at the bottom of my example has.

**Comment by joeybloggs** [comment]
Hey @fastest963 so I've been looking and thinking about this a bunch and come to a few conclusions:

It would be possible to handle this in the pre-parsed phase of the url.Values, but in doing so all values would need to start being grouped by namespace, eg. text between the periods

There are a few problems with this though the library would become 2-3x slower, possibly more because there is no guarantee the information is contiguous like with JSON and in fact won't be as url.Values is a map and therefore unordered. Moreover the more deeply nested the slower it would get.

I then started to think that just because I can doesn't mean I really should, it is not really how posted form data works. Although strides have be made to allow assigning values into nested structures, posted data is really about a single value equals a value or array of values; this is one of the reasons JSON and other similar interchange formats exist.

So I don't think that I would like to allow this, even if it may be possible, mainly because it could encourage the use of the wrong technology for the job at hand. It's like trying to make a square peg fit in a round hole, when other such formats are designed to handle nested structures.

I would very much like to hear your thoughts? perhaps I am being to rigid or idealistic?

**Comment by fastest963** [comment]
> It would be possible to handle this in the pre-parsed phase of the url.Values, but in doing so all values would need to start being grouped by namespace, eg. text between the periods

Yeah, that's what I'm currently doing essentially.

> There are a few problems with this though the library would become 2-3x slower, possibly more because there is no guarantee the information is contiguous like with JSON and in fact won't be as url.Values is a map and therefore unordered. Moreover the more deeply nested the slower it would get.

I don't think that's worth the benefit unless the slower mode could be optionally turned on.

> Although strides have be made to allow assigning values into nested structures, posted data is really about a single value equals a value or array of values; this is one of the reasons JSON and other similar interchange formats exist.

Yeah, I don't disagree with you. I just expected custom structs to work the same as regular structs. If I do `B[0].C=test` then the `C` field on `B` is set to `test` but the custom function can't handle fields like this.

> So I don't think that I would like to allow this, even if it may be possible, mainly because it could encourage the use of the wrong technology for the job at hand.

I agree with everything else you said but disagree with this sentence. While JSON would (and is) be a much better format for this type of data, there are cases in which you can't use JSON. Our service actually prefers JSON but we need to actually be able to accept the data via JSON and via url parameters because of external restrictions.

I appreciate your input and your thoughts on this and while it would be nice if the library supported this use case, I understand if it cannot. If it cannot be supported, then at least a small documentation update might be worth doing to clarify, since I originally thought it would be handled.

**Comment by joeybloggs** [comment]
Thanks @fastest963 for all your feedback! :smile:

>So I don't think that I would like to allow this, even if it may be possible, mainly because it could encourage the use of the wrong technology for the job at hand.
I agree with everything else you said but disagree with this sentence. While JSON would (and is) be a much better format for this type of data, there are cases in which you can't use JSON. Our service actually prefers JSON but we need to actually be able to accept the data via JSON and via url parameters because of external restrictions.

After reading this again I totally agree with you.

Some good news though, because of all of your great feedback I've been doing some brainstorming and think I may have found a way to accomplish this, it would require a breaking change to the CustomTypeFunc but it would make a great enhancement I think so worth it.

So within parseMapData I could ensure an entry for the struct gets added to the map,that way the custom function could get called, also add a double check within the struct case, just in case parseMapData wasn't called yet...And then the change to CustomTypeFunc could be passing just one more parameter...The url.Values..That way you'd have access to all URL vales and be able to create much more powerful custom logic as well.

It shouldn't slow much down...maybe a write and a couple of reads to a map... What do you think?

**Comment by joeybloggs** [comment]
Hey @fastest963 

ok so I gave this a try without success; it caused a lot of other problems and adds some more confusion as well because if a custom type is found the function is called and then the code continues on without diving into the struct and so if any other `url.Values` that should get st on the struct, they won't.

I think that it is best to keep the library as is and provide a documentation update.
