### ISSUE TITLE
Support map[string]interface{} decode, not just Struct

### ISSUE THREAD

**Issue by yatniel7** [go-playground/form#37]
Support map[string]interface{} decode, not just Struct

**Comment by yatniel7** [comment]
Direct support for decoding to map[string]interface

**Comment by joeybloggs** [comment]
I've been looking into this a bit, it seems possible, but keep in mind that the value portion of the map will always be 1 of 2 values:

- string
- []string

because there is no type information available.

**Comment by aeneasr** [comment]
I just stumbled on this - can you go into why it can only be 1 of 2 values? The JSON decoder is capable of properly identifying number/int/float against `map[string]interface{}` - what's different here?

**Comment by aeneasr** [comment]
In fact, it seems like [this](https://github.com/go-playground/form/pull/36) patch does exactly that, any reason for it not being merged yet?

**Comment by joeybloggs** [comment]
@aeneasr to answer your questions:

1. JSON itself has types in its design, see [here](https://cswr.github.io/JsonSchema/spec/basic_types/), and so is why the JSON decoder can identify types; however, it only decodes to 3 types bool, float64 and string because JSON does not provide detailed type information like `uint8`. Form information is all strings an arrays of strings and so there is no type information available, see the [url.Values](https://cswr.github.io/JsonSchema/spec/basic_types/) type signature.

2. The patch does not do "exactly that" as you put it, it still requires you to define schema by providing a structure that contains schema and types; it will also copy a lot of data and slow down the library, even if not being used. I've been thinking about it a lot and don't think I'm going to accept the PR because you can decode into your struct and there are many other libraries that can transform that into a `map[string]interface{}` to achieve the same.
