### ISSUE TITLE
Custom decoder accepts slice of string but expected to return single item

### ISSUE THREAD

**Issue by vearutop** [go-playground/form#39]
What is the reason to feed custom decoder with slice of strings? 

```
type DecodeCustomTypeFunc func([]string) (interface{}, error)
```
Decoder function is called at
```
func (d *decoder) setFieldByType(current reflect.Value, namespace []byte, idx int) (set bool) {
```
https://github.com/go-playground/form/blob/master/decoder.go#L191

If target field is a slice, `setFieldByType` is called in a loop with `idx` iterating through `[]string`. Internally custom decoder is called with that full `[]string` and without any mention of current `idx`. 

How decoder function is expected to deal with multi-element input?

To me it seems correct code should be 
```go
	val, err := cf([]string{arr[idx]})
```
but then I'm not sure why decoder function needs to accept a slice.

**Comment by joeybloggs** [comment]
Hey @vearutop apologies in advance for formatting, answering from my phone :)

so each value that is to be decoded is really a URL.Value which is type map[string][]string, that’s where the array of strings comes from that’s passed to the customer decoder functions.

As for not passing idx is because it’s not really needed because the custom decoding function is looked up by namespace, so there are only 2 possibilities:

1. The namespace is MyStruct.SliceField[0] and so the custom decoder function will only trigger for element 0 and so the index is already handled and not needed.

2. The namespace is MyStruct.SliceField and the custom decoder function will be passed the whole slice and so again idx won’t be needed as your operating on the whole slice.

Please let me know if that makes sense, sorry again about the formatting and lack of links

**Comment by vearutop** [comment]
Here is an example:
```
type customString string

func TestDecoder_RegisterCustomTypeFunc(t *testing.T) {
	type TestStruct struct {
		Slice []customString `form:"slice"`
	}

	d := NewDecoder()
	d.RegisterCustomTypeFunc(func(vals []string) (i interface{}, e error) {
		return customString("custom" + vals[0]), nil
	}, customString(""))

	var v TestStruct
	err := d.Decode(&v, url.Values{"slice": []string{"v1", "v2"}})
	Equal(t, err, nil)

	Equal(t, v, []customString{"customv1", "customv2"})

}
```
I would expect such test to pass, but it fails with:
```
{[customv1 customv1]} does not equal [customv1 customv2]
```

**Comment by joeybloggs** [comment]
ah now I understand, thanks @vearutop it is indeed a bug, fixing ASAP

**Comment by joeybloggs** [comment]
As a side note here is an alternative that will also give you what you want:
```go
package main

import (
	"net/url"
	"testing"

	"github.com/go-playground/form"
	. "gopkg.in/go-playground/assert.v1"
)

type customString string

func TestDecoder_RegisterCustomTypeFunc(t *testing.T) {
	type TestStruct struct {
		Slice []customString `form:"slice"`
	}

	d := form.NewDecoder()
	d.RegisterCustomTypeFunc(func(vals []string) (i interface{}, e error) {
		custom := make([]customString, 0, len(vals))
		for i := 0; i < len(vals); i++ {
			custom = append(custom, customString("custom"+vals[i]))
		}
		return custom, nil
	}, []customString{})

	var v TestStruct
	err := d.Decode(&v, url.Values{"slice": []string{"v1", "v2"}})
	Equal(t, err, nil)
	Equal(t, v.Slice, []customString{"customv1", "customv2"})
}

```
