### ISSUE TITLE
Decoder picks only one value when array is present in query params as Array[]=x&Array[]=y

### ISSUE THREAD

**Issue by ankitaSejal** [go-playground/form#60]
### Code sample, to showcase or reproduce:

```go

package main

import (
	"fmt"
	"log"
	"net/url"

	"github.com/go-playground/form/v4"
)

type PostsRequest struct {
	PostIds     []string
	Projections []string
}

var decoder *form.Decoder

func main() {
	decoder = form.NewDecoder()

	values := parseForm()

	var req PostsRequest

	err := decoder.Decode(&req, values)
	if err != nil {
		log.Panic(err)
	}

	fmt.Printf("%#v\n", req)
}

func parseForm() url.Values {
	return url.Values{
		"PostIds[]": []string{"1", "2"},
	}
}
```

**Comment by ankitaSejal** [comment]
Printed response is :
`main.PostsRequest{PostIds:[]string{"1"}, Projections:[]string(nil)}`

**Comment by deankarn** [comment]
@ankitaSejal There is a mismatch with the `struct field name` and the `url.Values` name which is why it appears to not be working. It's getting a single value set by total cooincidence of how the code flows(which I will be looking into further to prevent future confusion).

The struct field name is `PostIds` but the `url .Value` name is `PostIds[]`, hence the mismatch. The `PostIds[n]` syntax only works when an index is specified.

Adding the form field name like so should solve your issue OR changing the url.Value to drop the brackets `[]`
```go
	type PostsRequest struct {
		PostIds     []string `form:"PostIds[]"`
		Projections []string
	}
```

**Comment by deankarn** [comment]
I also updated the library to surface the issue to avoid confusion like this in the future https://github.com/go-playground/form/pull/61/files
