### ISSUE TITLE
<input type="checkbox"> decoding?

### ISSUE THREAD

**Issue by danhardman** [go-playground/form#8]
How does this package manage decoding of checkbox values as type `bool`? When parsing forms myself, I've always had to create a utility function to parse checkbox values:

``` go
func ParseCheckbox(checkbox string) (bool, error) {
	if checkbox == "on" {
		return true, nil
	} else if checkbox == "off" || checkbox == "" { //Empty = unchecked
		return false, nil
	}

	return false, errors.New("Invalid checkbox value. Must be \"on\" or \"off\".")
}
```

Any light shed on this would be appreciated!

**Comment by joeybloggs** [comment]
hey @danhardman 

I completely get where you're coming from, I've had the same troubles where the value passed down is `on` or `off` and Go's [strconv.ParseBool(...)](https://golang.org/src/strconv/atob.go?s=351:401#L1) doesn't handle those values.

so my [parseBool, seen here,](https://github.com/go-playground/form/blob/ec9eaa926768446bbd1e7f8fbc549027fc3b83ce/util.go#L34) handles all of Go's standard values plus a few extra, but otherwise mimics the function exactly. If more values are required and those values make sense, I'd be happy to add more.

```go
func parseBool(str string) (bool, error) {

	switch str {
	case "1", "t", "T", "true", "TRUE", "True", "on", "yes", "ok":
		return true, nil
	case "0", "f", "F", "false", "FALSE", "False", "off", "no":
		return false, nil
	}

	// strconv.NumError mimicing exactly the strconv.ParseBool(..) error and type
	// to ensure compatibility with std library and beyond.
	return false, &strconv.NumError{Func: "ParseBool", Num: str, Err: strconv.ErrSyntax}
}
```

**Comment by danhardman** [comment]
That seems to work fine on my tests, thanks for the info!
